[package]
name = "thermite"
version = "0.1.0"
authors = ["Andrew Bastien <volundmush@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8.1", features = ["v4", "serde"]}
actix = "0.10.0-alpha.1"
actix-web = "3.0.0-alpha.3"
actix-web-actors = "3.0.0-alpha.1"
actix-rt = "1.1.1"
bytes = "0.5.4"
flate2 = "1.0.16"
tokio = {version = "0.2.21", features = ["full"]}
tokio-util = "0.3.1"
nalgebra = "0.21.1"
